export const countryData: {
  [key: string]: { country: string; capital: string; language: string };
} = {
  ae: { country: "United Arab Emirates", capital: "Abu Dhabi", language: "ar" },
  ar: { country: "Argentina", capital: "Buenos Aires", language: "es" },
  au: { country: "Australia", capital: "Canberra", language: "en" },
  be: { country: "Belgium", capital: "Brussels", language: "nl" },
  bg: { country: "Bulgaria", capital: "Sofia", language: "bg" },
  br: { country: "Brazil", capital: "Brasília", language: "pt" },
  ca: { country: "Canada", capital: "Ottawa", language: "en" },
  ch: { country: "Switzerland", capital: "Bern", language: "de" },
  cn: { country: "China", capital: "Beijing", language: "zh" },
  co: { country: "Colombia", capital: "Bogotá", language: "es" },
  cu: { country: "Cuba", capital: "Havana", language: "es" },
  cz: { country: "Czech Republic", capital: "Prague", language: "cs" },
  de: { country: "Germany", capital: "Berlin", language: "de" },
  eg: { country: "Egypt", capital: "Cairo", language: "ar" },
  fr: { country: "France", capital: "Paris", language: "fr" },
  gb: { country: "United Kingdom", capital: "London", language: "en" },
  gr: { country: "Greece", capital: "Athens", language: "el" },
  hk: { country: "Hong Kong", capital: "Hong Kong", language: "zh" },
  hu: { country: "Hungary", capital: "Budapest", language: "hu" },
  id: { country: "Indonesia", capital: "Jakarta", language: "id" },
  ie: { country: "Ireland", capital: "Dublin", language: "en" },
  il: { country: "Israel", capital: "Jerusalem", language: "he" },
  in: { country: "India", capital: "New Delhi", language: "hi" },
  it: { country: "Italy", capital: "Rome", language: "it" },
  jp: { country: "Japan", capital: "Tokyo", language: "ja" },
  kr: { country: "South Korea", capital: "Seoul", language: "ko" },
  lb: { country: "Lebanon", capital: "Beirut", language: "ar" },
  lt: { country: "Lithuania", capital: "Vilnius", language: "lt" },
  lu: { country: "Luxembourg", capital: "Luxembourg City", language: "lb" },
  lv: { country: "Latvia", capital: "Riga", language: "lv" },
  ma: { country: "Morocco", capital: "Rabat", language: "ar" },
  mx: { country: "Mexico", capital: "Mexico City", language: "es" },
  my: { country: "Malaysia", capital: "Kuala Lumpur", language: "ms" },
  ng: { country: "Nigeria", capital: "Abuja", language: "en" },
  nl: { country: "Netherlands", capital: "Amsterdam", language: "nl" },
  no: { country: "Norway", capital: "Oslo", language: "no" },
  nz: { country: "New Zealand", capital: "Wellington", language: "en" },
  ph: { country: "Philippines", capital: "Manila", language: "fil" },
  pl: { country: "Poland", capital: "Warsaw", language: "pl" },
  pt: { country: "Portugal", capital: "Lisbon", language: "pt" },
  ro: { country: "Romania", capital: "Bucharest", language: "ro" },
  rs: { country: "Serbia", capital: "Belgrade", language: "sr" },
  ru: { country: "Russia", capital: "Moscow", language: "ru" },
  us: { country: "United States", capital: "Washington, D.C.", language: "en" },
};
