export const countryData: { [key: string]: { country: string; capital: string } } = {
  ae: { country: "United Arab Emirates", capital: "Abu Dhabi" },
  ar: { country: "Argentina", capital: "Buenos Aires" },
  au: { country: "Australia", capital: "Canberra" },
  be: { country: "Belgium", capital: "Brussels" },
  bg: { country: "Bulgaria", capital: "Sofia" },
  br: { country: "Brazil", capital: "Brasília" },
  ca: { country: "Canada", capital: "Ottawa" },
  ch: { country: "Switzerland", capital: "Bern" },
  cn: { country: "China", capital: "Beijing" },
  co: { country: "Colombia", capital: "Bogotá" },
  cu: { country: "Cuba", capital: "Havana" },
  cz: { country: "Czech Republic", capital: "Prague" },
  de: { country: "Germany", capital: "Berlin" },
  eg: { country: "Egypt", capital: "Cairo" },
  fr: { country: "France", capital: "Paris" },
  gb: { country: "United Kingdom", capital: "London" },
  gr: { country: "Greece", capital: "Athens" },
  hk: { country: "Hong Kong", capital: "Hong Kong" },
  hu: { country: "Hungary", capital: "Budapest" },
  id: { country: "Indonesia", capital: "Jakarta" },
  ie: { country: "Ireland", capital: "Dublin" },
  il: { country: "Israel", capital: "Jerusalem" },
  in: { country: "India", capital: "New Delhi" },
  it: { country: "Italy", capital: "Rome" },
  jp: { country: "Japan", capital: "Tokyo" },
  kr: { country: "South Korea", capital: "Seoul" },
  lb: { country: "Lebanon", capital: "Beirut" },
  lt: { country: "Lithuania", capital: "Vilnius" },
  lu: { country: "Luxembourg", capital: "Luxembourg City" },
  lv: { country: "Latvia", capital: "Riga" },
  ma: { country: "Morocco", capital: "Rabat" },
  mx: { country: "Mexico", capital: "Mexico City" },
  my: { country: "Malaysia", capital: "Kuala Lumpur" },
  ng: { country: "Nigeria", capital: "Abuja" },
  nl: { country: "Netherlands", capital: "Amsterdam" },
  no: { country: "Norway", capital: "Oslo" },
  nz: { country: "New Zealand", capital: "Wellington" },
  ph: { country: "Philippines", capital: "Manila" },
  pl: { country: "Poland", capital: "Warsaw" },
  pt: { country: "Portugal", capital: "Lisbon" },
  ro: { country: "Romania", capital: "Bucharest" },
  rs: { country: "Serbia", capital: "Belgrade" },
  ru: { country: "Russia", capital: "Moscow" },
  us: { country: "United States", capital: "Washington, D.C." },
};
